services:
  backend:
    build: .
    container_name: deno_backend
    ports:
      - "8001:8001"
    volumes:
      - ./public:/app/public
    env_file:
      - path: production.env
        required: true
    environment:
      - OTEL_DENO=true
      - OTEL_SERVICE_NAME=socialfolio-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4318
    depends_on:
      - mongo
      - redis
    networks:
      - proxy-network
      - backend-network

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:0.8.1
    container_name: monitoring_lgtm
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./lgtm/grafana:/data/grafana
      - ./lgtm/prometheus:/data/prometheus
      - ./lgtm/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    networks:
      - backend-network

  mongo:
    image: mongo:8.2.3
    container_name: mongo_db
    restart: always
    env_file:
      - path: production.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    env_file:
      - path: ./production.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  mongo_data:
  redis_data:

networks:
  proxy-network:
    external: true # This allows Nginx Proxy Manager to route traffic to backend
  backend-network:
    driver: bridge # Internal network for backend services
